//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_WebService.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IContratoServidor")]
    public interface IContratoServidor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoServidor/EnviaStrToServidor", ReplyAction="http://tempuri.org/IContratoServidor/EnviaStrToServidorResponse")]
        bool EnviaStrToServidor(string pMensagemEnviada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoServidor/EnviaStrToServidor", ReplyAction="http://tempuri.org/IContratoServidor/EnviaStrToServidorResponse")]
        System.Threading.Tasks.Task<bool> EnviaStrToServidorAsync(string pMensagemEnviada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoServidor/PegaStrFromServidor", ReplyAction="http://tempuri.org/IContratoServidor/PegaStrFromServidorResponse")]
        string PegaStrFromServidor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContratoServidor/PegaStrFromServidor", ReplyAction="http://tempuri.org/IContratoServidor/PegaStrFromServidorResponse")]
        System.Threading.Tasks.Task<string> PegaStrFromServidorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContratoServidorChannel : Cliente_WebService.ServiceReference.IContratoServidor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContratoServidorClient : System.ServiceModel.ClientBase<Cliente_WebService.ServiceReference.IContratoServidor>, Cliente_WebService.ServiceReference.IContratoServidor {
        
        public ContratoServidorClient() {
        }
        
        public ContratoServidorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContratoServidorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContratoServidorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContratoServidorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EnviaStrToServidor(string pMensagemEnviada) {
            return base.Channel.EnviaStrToServidor(pMensagemEnviada);
        }
        
        public System.Threading.Tasks.Task<bool> EnviaStrToServidorAsync(string pMensagemEnviada) {
            return base.Channel.EnviaStrToServidorAsync(pMensagemEnviada);
        }
        
        public string PegaStrFromServidor() {
            return base.Channel.PegaStrFromServidor();
        }
        
        public System.Threading.Tasks.Task<string> PegaStrFromServidorAsync() {
            return base.Channel.PegaStrFromServidorAsync();
        }
    }
}
